apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-ggve
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-ggve
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-ggve
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-ggve
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-ggve
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/dc-metro-map-ggve@sha256:f4c5e4652a57c73f0d92fb105506cf418d3f8bdd964864ccb19c4587062a38e7
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
