apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-qsla
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/devfile-sample-python-basic-qsla@sha256:938e29413bcd18e16f86cbe1b059998afa988da5c666f3a8b5eeca98648a2428
        name: my-python
        resources: {}
status: {}
